import os
import json
import smtplib
import logging
import secrets
import urllib.request
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from flask import Flask, request, jsonify, send_from_directory, session

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__, static_folder='.', static_url_path='')
_flask_secret = os.environ.get('FLASK_SECRET')
if not _flask_secret:
    logger.warning('FLASK_SECRET env var not set — admin sessions will not persist across restarts.')
    _flask_secret = secrets.token_hex(32)
app.secret_key = _flask_secret

COMPLAINTS_FILE = 'complaints_data.json'
APPLICATIONS_FILE = 'applications_data.json'
SERVER_STATUS_FILE = 'server_status.json'
BOLOS_FILE = 'bolos_data.json'
RADIO_LOG_FILE = 'radio_log.json'
CAD_DATA_FILE = 'cad_data.json'
ALERTS_FILE = 'alerts_data.json'
OFFICER_SESSIONS_FILE = 'officer_sessions.json'

DEFAULT_OFFICERS = [
    {'id': '1L-01',  'name': 'Chief Unit',      'status': 'Available', 'department': 'LSPD'},
    {'id': '2L-12',  'name': 'Patrol Unit',     'status': 'En Route',  'department': 'LSPD'},
    {'id': '3L-22',  'name': 'Traffic Unit',    'status': 'On Scene',  'department': 'Traffic Division'},
    {'id': 'D-04',   'name': 'Dispatch',        'status': 'Active',    'department': 'Dispatch'},
    {'id': 'K9-02',  'name': 'K9 Unit',         'status': 'Available', 'department': 'K9 Unit'},
    {'id': 'GU-01',  'name': 'Gang Unit 1',     'status': 'Available', 'department': 'Gang Enforcement'},
    {'id': 'GU-02',  'name': 'Gang Unit 2',     'status': 'Available', 'department': 'Gang Enforcement'},
    {'id': 'BCSO-1', 'name': 'BCSO Deputy 1',   'status': 'Available', 'department': 'BCSO'},
    {'id': 'BCSO-2', 'name': 'BCSO Deputy 2',   'status': 'Off Duty',  'department': 'BCSO'},
    {'id': 'SWT-1',  'name': 'SWAT Unit',       'status': 'Off Duty',  'department': 'SWAT'},
]

DEFAULT_CAD_DATA = {
    'civilians': [],
    'vehicles': [],
    'licenses': [],
    'warrants': [],
    'arrests': [],
    'incidents': [],
    'evidence': [],
    'trafficStops': [],
    'calls911': [],
    'officers': DEFAULT_OFFICERS,
    'activityLog': [],
}


def load_officer_sessions():
    if os.path.exists(OFFICER_SESSIONS_FILE):
        with open(OFFICER_SESSIONS_FILE, 'r') as f:
            return json.load(f)
    return {}


def save_officer_sessions(sessions):
    with open(OFFICER_SESSIONS_FILE, 'w') as f:
        json.dump(sessions, f, indent=2)


def load_alerts():
    if os.path.exists(ALERTS_FILE):
        with open(ALERTS_FILE, 'r') as f:
            return json.load(f)
    return []


def save_alerts(alerts):
    with open(ALERTS_FILE, 'w') as f:
        json.dump(alerts[-100:], f, indent=2)


def load_cad_data():
    if os.path.exists(CAD_DATA_FILE):
        with open(CAD_DATA_FILE, 'r') as f:
            stored = json.load(f)
        data = dict(DEFAULT_CAD_DATA)
        data.update(stored)
        return data
    return dict(DEFAULT_CAD_DATA)


def save_cad_data(data):
    with open(CAD_DATA_FILE, 'w') as f:
        json.dump(data, f, indent=2)

DEFAULT_STATUS = {
    'cityStatus': 'ACTIVE',
    'playerCount': 0,
    'maxPlayers': 32,
    'customMessage': '24/7 dispatch channel live',
    'lastUpdated': None
}


def load_bolos():
    if os.path.exists(BOLOS_FILE):
        with open(BOLOS_FILE, 'r') as f:
            return json.load(f)
    return []


def save_bolos(bolos):
    with open(BOLOS_FILE, 'w') as f:
        json.dump(bolos, f, indent=2)


def create_bolo(suspect_name, description, last_location, charges, officer, threat_level='High', vehicle=''):
    bolos = load_bolos()
    bolo = {
        'id': f"BOLO-{datetime.now().strftime('%Y%m%d%H%M%S')}-{len(bolos)+1:04d}",
        'suspectName': suspect_name,
        'description': description,
        'lastLocation': last_location,
        'vehicle': vehicle,
        'charges': charges,
        'threatLevel': threat_level,
        'issuedBy': officer,
        'issuedAt': datetime.now().isoformat(),
        'status': 'Active',
        'autoGenerated': True
    }
    bolos.insert(0, bolo)
    save_bolos(bolos)
    return bolo


def load_radio_log():
    if os.path.exists(RADIO_LOG_FILE):
        with open(RADIO_LOG_FILE, 'r') as f:
            return json.load(f)
    return []


def save_radio_log(log):
    with open(RADIO_LOG_FILE, 'w') as f:
        json.dump(log[-100:], f, indent=2)


def load_server_status():
    if os.path.exists(SERVER_STATUS_FILE):
        with open(SERVER_STATUS_FILE, 'r') as f:
            return json.load(f)
    return dict(DEFAULT_STATUS)


def save_server_status(status):
    status['lastUpdated'] = datetime.now().isoformat()
    with open(SERVER_STATUS_FILE, 'w') as f:
        json.dump(status, f, indent=2)
    return status


def load_applications():
    if os.path.exists(APPLICATIONS_FILE):
        with open(APPLICATIONS_FILE, 'r') as f:
            return json.load(f)
    return []


def save_applications(applications):
    with open(APPLICATIONS_FILE, 'w') as f:
        json.dump(applications, f, indent=2)


def save_application(data):
    applications = load_applications()
    data['id'] = f"APP-{datetime.now().strftime('%Y%m%d%H%M%S')}-{len(applications)+1:04d}"
    data['submittedAt'] = datetime.now().isoformat()
    data['status'] = 'Pending'
    data['staffNotes'] = ''
    applications.append(data)
    save_applications(applications)
    return data


def send_application_email(app):
    smtp_host = os.environ.get('SMTP_HOST', 'smtp.gmail.com')
    smtp_port = int(os.environ.get('SMTP_PORT', '465'))
    smtp_email = os.environ.get('SMTP_EMAIL')
    smtp_password = os.environ.get('SMTP_PASSWORD')
    notify_email = os.environ.get('NOTIFY_EMAIL', smtp_email)
    from_name = os.environ.get('SMTP_FROM_NAME', 'NThaCityRP')

    if not smtp_email or not smtp_password:
        logger.warning('Email credentials not configured. Application saved but no email sent.')
        return False

    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"[NThaCityRP] New Application — {app['applicationType']} — {app['id']}"
        msg['From'] = f"{from_name} <{smtp_email}>"
        msg['To'] = notify_email

        html = f"""
        <html><body style="font-family:Arial,sans-serif;background:#111;color:#eee;padding:24px;">
          <div style="max-width:600px;margin:0 auto;background:#1a1a1a;border-radius:12px;padding:24px;border:1px solid #333;">
            <h2 style="color:#ff2d2d;margin-top:0;">NThaCityRP — New Application Submitted</h2>
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="padding:8px 0;color:#aaa;width:40%;">Application ID</td><td style="padding:8px 0;font-weight:bold;">{app['id']}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Submitted At</td><td style="padding:8px 0;">{app['submittedAt']}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Discord</td><td style="padding:8px 0;">{app.get('appDiscord','N/A')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Character Name</td><td style="padding:8px 0;">{app.get('appCharacter','N/A')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Role Applied For</td><td style="padding:8px 0;"><strong style="color:#ff2d2d;">{app.get('applicationType','N/A')}</strong></td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Age</td><td style="padding:8px 0;">{app.get('ageConfirmation','N/A')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Availability</td><td style="padding:8px 0;">{app.get('availability','N/A')}</td></tr>
            </table>
            <hr style="border-color:#333;margin:16px 0;">
            <p style="color:#aaa;margin:4px 0;">RP Experience</p>
            <p style="background:#111;padding:12px;border-radius:8px;border-left:3px solid #ff2d2d;">{app.get('experience','N/A')}</p>
            <p style="color:#aaa;margin:4px 0;">Why They Want This Role</p>
            <p style="background:#111;padding:12px;border-radius:8px;border-left:3px solid #555;">{app.get('roleReason','N/A')}</p>
            <p style="color:#555;font-size:12px;margin-top:24px;">NThaCityRP Application System — Automated Notification</p>
          </div>
        </body></html>
        """

        plain = f"""
NThaCityRP — New Application Submitted
=======================================
Application ID: {app['id']}
Submitted At:   {app['submittedAt']}
Discord:        {app.get('appDiscord','N/A')}
Character:      {app.get('appCharacter','N/A')}
Role:           {app.get('applicationType','N/A')}
Age:            {app.get('ageConfirmation','N/A')}
Availability:   {app.get('availability','N/A')}

RP Experience:
{app.get('experience','N/A')}

Why This Role:
{app.get('roleReason','N/A')}
        """

        msg.attach(MIMEText(plain, 'plain'))
        msg.attach(MIMEText(html, 'html'))

        if smtp_port == 465:
            with smtplib.SMTP_SSL(smtp_host, smtp_port) as srv:
                srv.login(smtp_email, smtp_password)
                srv.sendmail(smtp_email, notify_email, msg.as_string())
        else:
            with smtplib.SMTP(smtp_host, smtp_port) as srv:
                srv.ehlo()
                srv.starttls()
                srv.login(smtp_email, smtp_password)
                srv.sendmail(smtp_email, notify_email, msg.as_string())

        logger.info(f"Application email sent for {app['id']}")
        return True
    except Exception as e:
        logger.error(f"Failed to send application email: {e}")
        return False


def send_application_discord(app):
    webhook_url = os.environ.get('DISCORD_WEBHOOK_URL', '')
    if not webhook_url or 'placeholder' in webhook_url:
        logger.warning('Discord webhook not configured. Skipping Discord notification.')
        return False

    try:
        type_colors = {
            'Police Department': 3447003,
            'EMS': 3066993,
            'Staff': 10181046,
            'Business Owner': 16744272,
            'Gang / Faction': 15158332,
            'Court / Judge / Lawyer': 16776960,
            'DMV Worker': 9807270,
        }
        color = type_colors.get(app.get('applicationType', ''), 3447003)

        payload = {
            "username": "NThaCityRP Applications",
            "avatar_url": "https://cdn.discordapp.com/embed/avatars/0.png",
            "embeds": [{
                "title": f"📋 New Application — {app.get('applicationType', 'Unknown')}",
                "description": f"**RP Experience:**\n{app.get('experience', 'N/A')}\n\n**Why This Role:**\n{app.get('roleReason', 'N/A')}",
                "color": color,
                "fields": [
                    {"name": "Application ID", "value": f"`{app['id']}`", "inline": True},
                    {"name": "Role", "value": app.get('applicationType', 'N/A'), "inline": True},
                    {"name": "Discord", "value": app.get('appDiscord', 'N/A'), "inline": True},
                    {"name": "Character", "value": app.get('appCharacter', 'N/A'), "inline": True},
                    {"name": "Age", "value": app.get('ageConfirmation', 'N/A'), "inline": True},
                    {"name": "Availability", "value": app.get('availability', 'N/A'), "inline": True},
                ],
                "footer": {"text": f"NThaCityRP Application System • {app['submittedAt'][:10]}"},
            }]
        }

        data = json.dumps(payload).encode('utf-8')
        req = urllib.request.Request(
            webhook_url, data=data,
            headers={'Content-Type': 'application/json'}, method='POST'
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status in (200, 204):
                logger.info(f"Discord notification sent for {app['id']}")
                return True
    except Exception as e:
        logger.error(f"Application Discord webhook failed: {e}")
    return False


def load_complaints():
    if os.path.exists(COMPLAINTS_FILE):
        with open(COMPLAINTS_FILE, 'r') as f:
            return json.load(f)
    return []


def save_complaints(complaints):
    with open(COMPLAINTS_FILE, 'w') as f:
        json.dump(complaints, f, indent=2)


def save_complaint(data):
    complaints = load_complaints()
    data['id'] = f"CMP-{datetime.now().strftime('%Y%m%d%H%M%S')}-{len(complaints)+1:04d}"
    data['submittedAt'] = datetime.now().isoformat()
    data['status'] = 'Open'
    data['staffNotes'] = ''
    complaints.append(data)
    save_complaints(complaints)
    return data


def send_email_notification(complaint):
    smtp_host = os.environ.get('SMTP_HOST', 'smtp.gmail.com')
    smtp_port = int(os.environ.get('SMTP_PORT', '465'))
    smtp_email = os.environ.get('SMTP_EMAIL')
    smtp_password = os.environ.get('SMTP_PASSWORD')
    notify_email = os.environ.get('NOTIFY_EMAIL', smtp_email)
    from_name = os.environ.get('SMTP_FROM_NAME', 'NThaCityRP')

    if not smtp_email or not smtp_password:
        logger.warning('Email credentials not configured. Complaint saved but no email sent.')
        return False

    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"[NThaCityRP] New Complaint — {complaint['complaintType']} — {complaint['id']}"
        msg['From'] = f"{from_name} <{smtp_email}>"
        msg['To'] = notify_email

        html = f"""
        <html><body style="font-family:Arial,sans-serif;background:#111;color:#eee;padding:24px;">
          <div style="max-width:600px;margin:0 auto;background:#1a1a1a;border-radius:12px;padding:24px;border:1px solid #333;">
            <h2 style="color:#ff2d2d;margin-top:0;">NThaCityRP — New Complaint Filed</h2>
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="padding:8px 0;color:#aaa;width:40%;">Complaint ID</td><td style="padding:8px 0;font-weight:bold;">{complaint['id']}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Submitted At</td><td style="padding:8px 0;">{complaint['submittedAt']}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Discord Username</td><td style="padding:8px 0;">{complaint.get('complaintDiscord','N/A')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Reported Person</td><td style="padding:8px 0;">{complaint.get('reportedName','N/A')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Complaint Type</td><td style="padding:8px 0;"><strong style="color:#ff2d2d;">{complaint.get('complaintType','N/A')}</strong></td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Incident Date/Time</td><td style="padding:8px 0;">{complaint.get('incidentDate','N/A')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Location/Channel</td><td style="padding:8px 0;">{complaint.get('incidentLocation','N/A')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Witnesses</td><td style="padding:8px 0;">{complaint.get('witnesses','None')}</td></tr>
              <tr><td style="padding:8px 0;color:#aaa;">Evidence Link</td><td style="padding:8px 0;">{complaint.get('evidenceLink','None')}</td></tr>
            </table>
            <hr style="border-color:#333;margin:16px 0;">
            <p style="color:#aaa;margin:4px 0;">Description</p>
            <p style="background:#111;padding:12px;border-radius:8px;border-left:3px solid #ff2d2d;">{complaint.get('description','N/A')}</p>
            <p style="color:#aaa;margin:4px 0;">Desired Resolution</p>
            <p style="background:#111;padding:12px;border-radius:8px;border-left:3px solid #555;">{complaint.get('resolution','N/A')}</p>
            <p style="color:#555;font-size:12px;margin-top:24px;">NThaCityRP Complaint System — Automated Notification</p>
          </div>
        </body></html>
        """

        plain = f"""
NThaCityRP — New Complaint Filed
=================================
Complaint ID:     {complaint['id']}
Submitted At:     {complaint['submittedAt']}
Discord Username: {complaint.get('complaintDiscord','N/A')}
Reported Person:  {complaint.get('reportedName','N/A')}
Complaint Type:   {complaint.get('complaintType','N/A')}
Incident Date:    {complaint.get('incidentDate','N/A')}
Location:         {complaint.get('incidentLocation','N/A')}
Witnesses:        {complaint.get('witnesses','None')}
Evidence Link:    {complaint.get('evidenceLink','None')}

Description:
{complaint.get('description','N/A')}

Desired Resolution:
{complaint.get('resolution','N/A')}
        """

        msg.attach(MIMEText(plain, 'plain'))
        msg.attach(MIMEText(html, 'html'))

        if smtp_port == 465:
            with smtplib.SMTP_SSL(smtp_host, smtp_port) as srv:
                srv.login(smtp_email, smtp_password)
                srv.sendmail(smtp_email, notify_email, msg.as_string())
        else:
            with smtplib.SMTP(smtp_host, smtp_port) as srv:
                srv.ehlo()
                srv.starttls()
                srv.login(smtp_email, smtp_password)
                srv.sendmail(smtp_email, notify_email, msg.as_string())

        logger.info(f"Email notification sent for complaint {complaint['id']}")
        return True

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


def send_discord_notification(complaint):
    webhook_url = os.environ.get('DISCORD_WEBHOOK_URL', '')
    if not webhook_url or 'placeholder' in webhook_url:
        logger.warning('Discord webhook not configured. Skipping Discord notification.')
        return False

    try:
        type_colors = {
            'Player report': 15158332,
            'Staff complaint': 15105570,
            'Officer complaint': 15548997,
            'Rule break': 16711680,
            'Fail RP': 16744272,
            'RDM / VDM': 16711680,
            'Harassment': 15158332,
            'Evidence submission': 3447003,
        }
        color = type_colors.get(complaint.get('complaintType', ''), 15158332)

        fields = [
            {"name": "Complaint ID", "value": f"`{complaint['id']}`", "inline": True},
            {"name": "Type", "value": complaint.get('complaintType', 'N/A'), "inline": True},
            {"name": "Reported Person", "value": complaint.get('reportedName', 'N/A'), "inline": True},
            {"name": "Discord", "value": complaint.get('complaintDiscord', 'N/A'), "inline": True},
            {"name": "Location", "value": complaint.get('incidentLocation', 'N/A'), "inline": True},
            {"name": "Incident Date", "value": complaint.get('incidentDate', 'N/A'), "inline": True},
        ]
        if complaint.get('witnesses'):
            fields.append({"name": "Witnesses", "value": complaint['witnesses'], "inline": False})
        if complaint.get('evidenceLink'):
            fields.append({"name": "Evidence", "value": complaint['evidenceLink'], "inline": False})

        payload = {
            "username": "NThaCityRP Complaints",
            "avatar_url": "https://cdn.discordapp.com/embed/avatars/0.png",
            "embeds": [{
                "title": f"🚨 New Complaint Filed — {complaint.get('complaintType', 'Unknown')}",
                "description": f"**Description:**\n{complaint.get('description', 'N/A')}\n\n**Desired Resolution:**\n{complaint.get('resolution', 'N/A')}",
                "color": color,
                "fields": fields,
                "footer": {"text": f"NThaCityRP Complaint System • {complaint['submittedAt'][:10]}"},
            }]
        }

        data = json.dumps(payload).encode('utf-8')
        req = urllib.request.Request(
            webhook_url,
            data=data,
            headers={'Content-Type': 'application/json'},
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status in (200, 204):
                logger.info(f"Discord notification sent for {complaint['id']}")
                return True
    except Exception as e:
        logger.error(f"Discord webhook failed: {e}")
    return False


def admin_required(f):
    from functools import wraps
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('admin_logged_in'):
            return jsonify({'success': False, 'error': 'Unauthorized'}), 401
        return f(*args, **kwargs)
    return decorated


@app.route('/api/admin/login', methods=['POST'])
def admin_login():
    data = request.get_json(silent=True) or {}
    password = data.get('password', '')
    admin_password = os.environ.get('ADMIN_PASSWORD', '')
    if password == admin_password:
        session['admin_logged_in'] = True
        return jsonify({'success': True})
    return jsonify({'success': False, 'error': 'Invalid password'}), 401


@app.route('/api/admin/logout', methods=['POST'])
def admin_logout():
    session.clear()
    return jsonify({'success': True})


@app.route('/api/admin/session', methods=['GET'])
def admin_session():
    return jsonify({'loggedIn': bool(session.get('admin_logged_in'))})


@app.route('/api/complaint', methods=['POST'])
def submit_complaint():
    data = request.get_json(silent=True) or {}
    required = ['complaintDiscord', 'reportedName', 'complaintType', 'incidentDate', 'incidentLocation', 'description', 'resolution']
    missing = [f for f in required if not data.get(f)]
    if missing:
        return jsonify({'success': False, 'error': f"Missing required fields: {', '.join(missing)}"}), 400

    complaint = save_complaint(data)
    email_sent = send_email_notification(complaint)
    send_discord_notification(complaint)

    return jsonify({
        'success': True,
        'id': complaint['id'],
        'emailSent': email_sent,
        'message': 'Complaint submitted successfully. Staff will review it shortly.'
    })


@app.route('/api/complaints', methods=['GET'])
@admin_required
def list_complaints():
    complaints = load_complaints()
    complaints.sort(key=lambda c: c.get('submittedAt', ''), reverse=True)
    return jsonify({'complaints': complaints, 'total': len(complaints)})


@app.route('/api/complaint/<complaint_id>/status', methods=['POST'])
@admin_required
def update_complaint_status(complaint_id):
    data = request.get_json(silent=True) or {}
    new_status = data.get('status')
    staff_notes = data.get('staffNotes')
    valid_statuses = ['Open', 'Under Review', 'Resolved', 'Dismissed']
    if new_status and new_status not in valid_statuses:
        return jsonify({'success': False, 'error': 'Invalid status'}), 400

    complaints = load_complaints()
    for c in complaints:
        if c['id'] == complaint_id:
            if new_status:
                c['status'] = new_status
                c['updatedAt'] = datetime.now().isoformat()
            if staff_notes is not None:
                c['staffNotes'] = staff_notes
            save_complaints(complaints)
            return jsonify({'success': True, 'complaint': c})

    return jsonify({'success': False, 'error': 'Complaint not found'}), 404


@app.route('/api/complaint/<complaint_id>', methods=['DELETE'])
@admin_required
def delete_complaint(complaint_id):
    complaints = load_complaints()
    original_len = len(complaints)
    complaints = [c for c in complaints if c['id'] != complaint_id]
    if len(complaints) == original_len:
        return jsonify({'success': False, 'error': 'Complaint not found'}), 404
    save_complaints(complaints)
    return jsonify({'success': True})


@app.route('/api/application', methods=['POST'])
def submit_application():
    data = request.get_json(silent=True) or {}
    required = ['appDiscord', 'appCharacter', 'applicationType', 'ageConfirmation', 'experience', 'roleReason', 'availability']
    missing = [f for f in required if not data.get(f)]
    if missing:
        return jsonify({'success': False, 'error': f"Missing required fields: {', '.join(missing)}"}), 400

    application = save_application(data)
    send_application_email(application)
    send_application_discord(application)

    return jsonify({
        'success': True,
        'id': application['id'],
        'message': 'Application submitted successfully. Staff will review it and contact you via Discord.'
    })


@app.route('/api/applications', methods=['GET'])
@admin_required
def list_applications():
    applications = load_applications()
    applications.sort(key=lambda a: a.get('submittedAt', ''), reverse=True)
    return jsonify({'applications': applications, 'total': len(applications)})


@app.route('/api/application/<app_id>/status', methods=['POST'])
@admin_required
def update_application_status(app_id):
    data = request.get_json(silent=True) or {}
    new_status = data.get('status')
    staff_notes = data.get('staffNotes')
    valid_statuses = ['Pending', 'Under Review', 'Accepted', 'Denied']
    if new_status and new_status not in valid_statuses:
        return jsonify({'success': False, 'error': 'Invalid status'}), 400

    applications = load_applications()
    for a in applications:
        if a['id'] == app_id:
            if new_status:
                a['status'] = new_status
                a['updatedAt'] = datetime.now().isoformat()
            if staff_notes is not None:
                a['staffNotes'] = staff_notes
            save_applications(applications)
            return jsonify({'success': True, 'application': a})

    return jsonify({'success': False, 'error': 'Application not found'}), 404


@app.route('/api/application/<app_id>', methods=['DELETE'])
@admin_required
def delete_application(app_id):
    applications = load_applications()
    original_len = len(applications)
    applications = [a for a in applications if a['id'] != app_id]
    if len(applications) == original_len:
        return jsonify({'success': False, 'error': 'Application not found'}), 404
    save_applications(applications)
    return jsonify({'success': True})


@app.route('/api/server-status', methods=['GET'])
def get_server_status():
    return jsonify(load_server_status())


def send_status_discord_notification(old_status, new_status):
    webhook_url = os.environ.get('DISCORD_WEBHOOK_URL', '')
    if not webhook_url or 'placeholder' in webhook_url:
        logger.warning('Discord webhook not configured. Skipping status notification.')
        return False

    status_colors = {
        'ACTIVE':      0x4caf50,
        'OFFLINE':     0x555555,
        'MAINTENANCE': 0x4a9eff,
        'WHITELIST':   0xf5a623,
    }
    status_emojis = {
        'ACTIVE':      '🟢',
        'OFFLINE':     '🔴',
        'MAINTENANCE': '🔵',
        'WHITELIST':   '🟡',
    }

    city = new_status.get('cityStatus', 'ACTIVE')
    color = status_colors.get(city, 0x555555)
    emoji = status_emojis.get(city, '⚪')

    old_city = old_status.get('cityStatus', 'ACTIVE')
    changed = old_city != city
    title = f"{emoji} City Status Changed: {old_city} → {city}" if changed else f"{emoji} City Status Updated: {city}"

    fields = [
        {"name": "City Status", "value": city, "inline": True},
        {"name": "Players Online", "value": f"{new_status.get('playerCount', 0)} / {new_status.get('maxPlayers', 32)}", "inline": True},
    ]
    if new_status.get('customMessage'):
        fields.append({"name": "Message", "value": new_status['customMessage'], "inline": False})

    payload = {
        "username": "NThaCityRP Status",
        "avatar_url": "https://cdn.discordapp.com/embed/avatars/0.png",
        "embeds": [{
            "title": title,
            "color": color,
            "fields": fields,
            "footer": {"text": f"NThaCityRP • {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}"},
        }]
    }

    try:
        data = json.dumps(payload).encode('utf-8')
        req = urllib.request.Request(
            webhook_url,
            data=data,
            headers={'Content-Type': 'application/json'},
            method='POST'
        )
        urllib.request.urlopen(req, timeout=5)
        logger.info('Status Discord notification sent.')
        return True
    except Exception as e:
        logger.error(f'Failed to send status Discord notification: {e}')
        return False


@app.route('/api/server-status', methods=['POST'])
@admin_required
def update_server_status():
    data = request.get_json(silent=True) or {}
    old_status = load_server_status()
    status = dict(old_status)
    valid_statuses = ['ACTIVE', 'OFFLINE', 'MAINTENANCE', 'WHITELIST']
    if 'cityStatus' in data and data['cityStatus'] in valid_statuses:
        status['cityStatus'] = data['cityStatus']
    if 'playerCount' in data:
        try:
            status['playerCount'] = max(0, int(data['playerCount']))
        except (ValueError, TypeError):
            pass
    if 'maxPlayers' in data:
        try:
            status['maxPlayers'] = max(1, int(data['maxPlayers']))
        except (ValueError, TypeError):
            pass
    if 'customMessage' in data:
        status['customMessage'] = str(data['customMessage'])[:200]
    save_server_status(status)
    send_status_discord_notification(old_status, status)
    return jsonify({'success': True, 'status': status})


@app.route('/api/bolos', methods=['GET'])
def get_bolos():
    return jsonify(load_bolos())


@app.route('/api/bolo', methods=['POST'])
def post_bolo():
    data = request.get_json(silent=True) or {}
    required = ['suspectName', 'description', 'lastLocation', 'threatLevel', 'issuedBy']
    if not all(data.get(f) for f in required):
        return jsonify({'success': False, 'error': 'Missing required fields.'}), 400
    bolos = load_bolos()
    bolo = {
        'id': f"BOLO-{datetime.now().strftime('%Y%m%d%H%M%S')}-{len(bolos)+1:04d}",
        'suspectName': data.get('suspectName', 'Unknown'),
        'description': data.get('description', ''),
        'lastLocation': data.get('lastLocation', ''),
        'vehicle': data.get('vehicle', ''),
        'charges': data.get('charges', ''),
        'threatLevel': data.get('threatLevel', 'Medium'),
        'issuedBy': data.get('issuedBy', ''),
        'issuedAt': datetime.now().isoformat(),
        'status': 'Active'
    }
    bolos.insert(0, bolo)
    save_bolos(bolos)
    return jsonify({'success': True, 'bolo': bolo})


@app.route('/api/bolo/<bolo_id>/clear', methods=['POST'])
def clear_bolo(bolo_id):
    bolos = load_bolos()
    for b in bolos:
        if b['id'] == bolo_id:
            b['status'] = 'Cleared'
            save_bolos(bolos)
            return jsonify({'success': True})
    return jsonify({'success': False, 'error': 'BOLO not found.'}), 404


@app.route('/api/ai/use-of-force', methods=['POST'])
def ai_use_of_force():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured.'}), 503

    data = request.get_json(silent=True) or {}
    officer       = data.get('officer', 'Unknown').strip()
    subject       = data.get('subject', 'Unknown').strip()
    location      = data.get('location', 'Unknown').strip()
    force_type    = data.get('forceType', '').strip()
    resistance    = data.get('resistance', '').strip()
    incident_desc = data.get('incidentDesc', '').strip()
    charges       = data.get('charges', '').strip()
    injuries      = data.get('injuries', '').strip()
    weapons       = data.get('weaponsObserved', 'No').strip()
    bodycam       = data.get('bodycam', 'Yes').strip()

    system_msg = """You are an AI-powered Computer Aided Dispatch (CAD) and legal report-writing system for NThaCityRP, a GTA V roleplay server set in Los Santos.
LOCATION RULES (CRITICAL): ALL locations must reference real GTA V map areas — Davis, Strawberry, Mission Row, Vespucci, Del Perro, Mirror Park, Route 68, Senora Freeway, Legion Square, Pillbox Hill Medical Center, Maze Bank Arena, etc.
USE OF FORCE REPORTS must be court-defensible: internally consistent, no contradictions, avoid vague phrases like 'acted suspicious', use only observable behaviour (e.g. 'subject repeatedly reached into waistband and ignored verbal commands'). Every escalation step must be justified. Force must match threat level. Flag any missing critical data as UNKNOWN – REQUIRES OFFICER INPUT."""

    user_msg = f"""Generate a complete Use of Force Report for NThaCityRP LSPD. Respond with ONLY a valid JSON object with these exact keys:

- "reportId": a realistic LSPD case number string (e.g. "UOF-2026-0047")
- "dateTime": today's date + a realistic time string (e.g. "May 05, 2026 — 22:14 hrs")
- "location": GTA V formatted location — convert any vague input to nearest GTA V equivalent
- "officerInvolved": officer name / badge
- "subjectInvolved": subject name
- "incidentSummary": 2-3 sentence objective overview of the incident
- "forceType": one of ["Presence", "Verbal Commands", "Physical Control", "Less Lethal (Taser/Baton)", "Lethal Force (Firearm)"]
- "reasonForForce": 2-3 sentences explaining exactly what the subject did to necessitate force, using observable behaviour only
- "resistanceLevel": one of ["Compliant", "Passive Resistance", "Active Resistance", "Assaultive", "Life-Threatening"]
- "threatAssessment": object with "weaponsObserved" (bool), "threatToOfficer" (bool), "threatToPublic" (bool), each with a one-sentence explanation
- "legalJustification": 3-4 sentence court-defensible paragraph tying officer actions to subject behaviour, emphasising proportional response under LSPD use-of-force policy
- "forceTimeline": array of 4-6 short step strings (e.g. ["Officer arrived at scene", "Initial verbal commands given", ...])
- "medicalAftercare": object with "emsRequested" (bool), "injuriesObserved" (string), "treatmentProvided" (string)
- "evidence": object with "bodycam" (bool), "witnesses" (string), "sceneEvidence" (string)
- "disposition": one of ["Arrested", "Hospitalized", "Arrested + Hospitalized", "Released — No Charges", "Deceased"]
- "chargesRecommended": comma-separated string of recommended charges (e.g. "Assault on Officer, Resisting Arrest")
- "liabilityWarning": string — if any critical justification data is missing or force seems disproportionate, return a warning starting with "⚠️ REPORT MAY BE LEGALLY WEAK –". Otherwise return empty string.
- "suspectFled": boolean — true if subject evaded or escaped, false otherwise
- "lastKnownLocation": if suspectFled true, specific GTA V street/area; otherwise empty string

Officer: {officer}
Subject: {subject}
Location: {location}
Force Type Used: {force_type if force_type else 'Not specified'}
Resistance Level: {resistance if resistance else 'Not specified'}
Weapons Observed: {weapons}
Bodycam: {bodycam}
Injuries: {injuries if injuries else 'None reported'}
Charges: {charges if charges else 'Not specified'}
Incident Description: {incident_desc if incident_desc else 'Not provided'}

Respond only with the JSON object. No markdown, no extra text."""

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [
                {'role': 'system', 'content': system_msg},
                {'role': 'user', 'content': user_msg}
            ],
            'max_tokens': 900,
            'temperature': 0.5,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://openrouter.ai/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=25) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            auto_bolo = None
            if ai_json.get('suspectFled'):
                auto_bolo = create_bolo(
                    suspect_name=subject,
                    description=f'Subject fled after use-of-force incident. {incident_desc[:120] if incident_desc else ""}',
                    last_location=ai_json.get('lastKnownLocation', '') or location,
                    charges=charges or ai_json.get('chargesRecommended', ''),
                    officer=officer,
                    threat_level='High'
                )
            return jsonify({'success': True, 'report': ai_json, 'autoBolo': auto_bolo})
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter UOF error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}.'}), 502
    except Exception as e:
        logger.error(f'AI UOF generation failed: {e}')
        return jsonify({'success': False, 'error': 'Report generation failed. Try again.'}), 500


@app.route('/api/ai/generate-bolo', methods=['POST'])
def ai_generate_bolo():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured.'}), 503

    data = request.get_json(silent=True) or {}
    charges = data.get('charges', '').strip()

    system_msg = """You are an AI-powered Computer Aided Dispatch (CAD) system for NThaCityRP, a GTA V roleplay server set in Los Santos.
LOCATION RULES (CRITICAL): ALL locations must be real GTA V map areas — Davis, Strawberry, Mission Row, Vespucci, Del Perro, Mirror Park, Rockford Hills, Sandy Shores, Route 68, Senora Freeway, Legion Square, Pillbox Hill, Maze Bank Arena, LSIA, La Mesa, Cypress Flats, etc.
VEHICLES: Use GTA V vehicle names — Baller, Dominator, Sultan, Kuruma, Sentinel, Schafter, Issi, Elegy, Banshee, Sandking, Granger, etc.
Generate realistic RP suspect profiles. No real-world references."""

    charge_hint = f" The suspect is wanted for: {charges}." if charges else " Pick a realistic crime scenario."

    user_msg = f"""Generate a realistic BOLO (Be On the Lookout) notice for an LSPD officer.{charge_hint}

Respond with ONLY a valid JSON object with these exact keys:
- "suspectName": realistic full name OR "Unknown Male" / "Unknown Female" if identity unconfirmed
- "description": 2-sentence physical description (gender, approx age, build, hair, clothing, distinguishing features like tattoos/scars)
- "lastLocation": specific GTA V street + area (e.g. "Covenant Ave & Forum Dr, Davis")
- "vehicle": GTA V vehicle name + color + partial plate (e.g. "Navy Blue Baller, partial plate 4KX") or "On foot" if no vehicle
- "charges": 1-3 charge strings (e.g. "Armed Robbery, Possession of Illegal Firearm")
- "threatLevel": "High", "Medium", or "Low" — based on severity of charges

Respond only with the JSON object. No markdown, no extra text."""

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [
                {'role': 'system', 'content': system_msg},
                {'role': 'user', 'content': user_msg}
            ],
            'max_tokens': 350,
            'temperature': 0.85,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://openrouter.ai/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            return jsonify({'success': True, 'bolo': ai_json})
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter generate-bolo error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}.'}), 502
    except Exception as e:
        logger.error(f'AI BOLO generation failed: {e}')
        return jsonify({'success': False, 'error': 'BOLO generation failed. Try again.'}), 500


@app.route('/api/ai/police-report', methods=['POST'])
def ai_police_report():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured. Add it in your environment secrets.'}), 503

    data = request.get_json(silent=True) or {}
    suspect = data.get('suspectName', 'Unknown')
    charges = data.get('charges', 'Unknown')
    officer = data.get('arrestingOfficer', 'Unknown')
    location = data.get('arrestLocation', 'Unknown')
    evidence = data.get('evidenceAttached', 'None')
    penalty = data.get('penalty', 'Unknown')
    notes = data.get('reportNotes', '')

    system_msg = """You are an AI-powered Computer Aided Dispatch (CAD) system and report-writing assistant for a GTA V roleplay server called NThaCityRP set in Los Santos.
LOCATION RULES (CRITICAL): ALL locations must reference GTA V map areas, streets, or landmarks such as Davis, Strawberry, Mission Row, Vespucci, Del Perro, Mirror Park, Route 68, Great Ocean Highway, Senora Freeway, Legion Square, Pillbox Hill Medical Center, Maze Bank Arena. If a vague location is given, convert it to the closest GTA V equivalent.
Maintain a professional law enforcement tone. No breaking RP immersion. No real-world cities."""

    user_msg = f"""Generate an INCIDENT REPORT for the following arrest. Respond with ONLY a valid JSON object with exactly four keys:
- "narrative": a formal, professional arrest narrative (150-220 words, third-person past tense). Use INCIDENT REPORT MODE structure: include Date/Time, Location (GTA V formatted), Reporting Officer, Involved Parties, Incident Type, Narrative, Actions Taken, Evidence, Disposition.
- "suggestedPenalty": a short realistic penalty string (e.g. "3 years / $25,000 fine") based on the charges — if already provided, refine and return it.
- "suspectFled": boolean true if the narrative indicates the suspect evaded, escaped, fled, or was not apprehended — otherwise false.
- "lastKnownLocation": if suspectFled is true, a specific GTA V street/area where the suspect was last seen (e.g. "Elgin Ave & Adam's Apple Blvd, Strawberry") — otherwise empty string.

Suspect: {suspect}
Charges: {charges}
Arresting Officer: {officer}
Arrest Location: {location}
Evidence: {evidence}
Current Penalty: {penalty if penalty else 'Not specified'}
Officer Notes: {notes if notes else 'None provided'}

Respond only with the JSON object. No markdown, no extra text."""

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [{'role': 'user', 'content': prompt}],
            'max_tokens': 500,
            'temperature': 0.7,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://api.openrouter.io/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            suspect_fled = ai_json.get('suspectFled', False)
            auto_bolo = None
            if suspect_fled:
                last_loc = ai_json.get('lastKnownLocation', '') or location
                auto_bolo = create_bolo(
                    suspect_name=suspect,
                    description=f'Suspect fled scene. Charges: {charges}.',
                    last_location=last_loc,
                    charges=charges,
                    officer=officer,
                    threat_level='High'
                )
                logger.info(f'Auto-BOLO created for {suspect} — fled scene')
            return jsonify({
                'success': True,
                'narrative': ai_json.get('narrative', ''),
                'suggestedPenalty': ai_json.get('suggestedPenalty', ''),
                'suspectFled': suspect_fled,
                'autoBolo': auto_bolo
            })
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter API error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}: check your API key and billing.'}), 502
    except Exception as e:
        logger.error(f'AI report generation failed: {e}')
        return jsonify({'success': False, 'error': 'Report generation failed. Try again.'}), 500


@app.route('/api/radio-log', methods=['GET'])
def get_radio_log():
    log = load_radio_log()
    return jsonify(list(reversed(log[-50:])))


@app.route('/api/radio-log', methods=['POST'])
def post_radio_log():
    data = request.get_json(silent=True) or {}
    unit = data.get('unit', '').strip()
    channel = data.get('channel', 'Primary').strip()
    message = data.get('message', '').strip()
    if not unit or not message:
        return jsonify({'success': False, 'error': 'Unit and message are required.'}), 400
    log = load_radio_log()
    entry = {
        'id': f"RADIO-{datetime.now().strftime('%Y%m%d%H%M%S')}-{len(log)+1:04d}",
        'unit': unit,
        'channel': channel,
        'message': message,
        'timestamp': datetime.now().isoformat()
    }
    log.append(entry)
    save_radio_log(log)
    return jsonify({'success': True, 'entry': entry})


@app.route('/api/ai/dispatch', methods=['POST'])
def ai_dispatch():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured.'}), 503

    data = request.get_json(silent=True) or {}
    caller = data.get('callerName', 'Unknown')
    location = data.get('location', 'Unknown')
    description = data.get('description', '')

    system_msg = """You are an AI-powered Computer Aided Dispatch (CAD) system for NThaCityRP, a GTA V roleplay server set in Los Santos.
LOCATION RULES (CRITICAL): ALL locations must reference GTA V map areas — Davis, Strawberry, Mission Row, Vespucci, Del Perro, Mirror Park, Route 68, Senora Freeway, Legion Square, Pillbox Hill, Maze Bank Arena, etc. Convert vague locations to nearest GTA V equivalent.
DISPATCH LOGIC: Assign units using LSPD format (e.g. LSPD-1A23, LSPD-2B04) for city calls, BCSO format (e.g. BCSO-3C11) for county/highway calls, K9-01/K9-02 for dog units, AIR-1 for helicopter. Escalate priority for weapons, violence, or pursuit. Suggest backup when warranted.
Maintain professional law enforcement tone. No real-world city references."""

    user_msg = f"""Triage this 911 call using DISPATCH LOGIC. Respond with ONLY a valid JSON object with these exact keys:
- "incidentType": one of exactly ["Robbery", "Assault", "Suspicious activity", "Traffic accident", "Shots fired", "Domestic disturbance", "Drug activity", "Pursuit", "Hostage situation", "Noise complaint"]
- "priority": one of exactly ["Critical", "High", "Medium", "Low"] — Critical=active threat/shots/hostage, High=robbery/assault in progress, Medium=suspicious/drugs, Low=noise/minor
- "assignedUnit": realistic LSPD/BCSO unit designation based on location and incident type (e.g. "LSPD-1A23", "BCSO-2B11", "K9-02", "AIR-1")
- "status": always "New"
- "triage": one dispatcher-style sentence (max 20 words) summarising the call with GTA V location reference

Caller: {caller}
Location: {location}
Description: {description if description else 'No description provided'}

Respond only with the JSON object. No markdown, no extra text."""

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [
                {'role': 'system', 'content': system_msg},
                {'role': 'user', 'content': user_msg}
            ],
            'max_tokens': 200,
            'temperature': 0.4,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://openrouter.ai/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            return jsonify({
                'success': True,
                'incidentType': ai_json.get('incidentType', ''),
                'priority': ai_json.get('priority', ''),
                'assignedUnit': ai_json.get('assignedUnit', ''),
                'status': ai_json.get('status', 'New'),
                'triage': ai_json.get('triage', '')
            })
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter dispatch error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}: check your API key.'}), 502
    except Exception as e:
        logger.error(f'AI dispatch triage failed: {e}')
        return jsonify({'success': False, 'error': 'Triage failed. Try again.'}), 500


@app.route('/api/ai/warrant', methods=['POST'])
def ai_warrant():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured.'}), 503

    data = request.get_json(silent=True) or {}
    suspect = data.get('warrantName', 'Unknown')
    charges = data.get('warrantCharges', 'Unknown')
    issuer = data.get('warrantIssuer', 'Unknown')
    existing_notes = data.get('warrantNotes', '')

    system_msg = """You are an AI-powered Computer Aided Dispatch (CAD) system and report-writing assistant for NThaCityRP, a GTA V roleplay server set in Los Santos.
LOCATION RULES (CRITICAL): ALL locations must reference GTA V map areas — Davis, Strawberry, Mission Row, Vespucci, Del Perro, Mirror Park, Route 68, Senora Freeway, Legion Square, Pillbox Hill, Maze Bank Arena, etc.
Write in professional law enforcement language. Ground all references in Los Santos / San Andreas. No real-world city names."""

    user_msg = f"""Generate an arrest warrant justification. Respond with ONLY a valid JSON object with exactly two keys:
- "justification": a formal probable-cause warrant justification (80-130 words) written in official LSPD legal language. Reference GTA V locations where relevant. Include probable cause, evidence basis, and the threat to public safety in Los Santos.
- "suggestedStatus": always return "Active"

Suspect: {suspect}
Charges: {charges}
Issued By: {issuer}
Additional Notes: {existing_notes if existing_notes else 'None'}

Respond only with the JSON object. No markdown, no extra text."""

    from datetime import timedelta
    expiration_date = (datetime.now() + timedelta(days=30)).strftime('%Y-%m-%d')

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [
                {'role': 'system', 'content': system_msg},
                {'role': 'user', 'content': user_msg}
            ],
            'max_tokens': 300,
            'temperature': 0.7,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://openrouter.ai/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            return jsonify({
                'success': True,
                'justification': ai_json.get('justification', ''),
                'suggestedStatus': ai_json.get('suggestedStatus', 'Active'),
                'suggestedExpiration': expiration_date
            })
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter warrant error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}: check your API key.'}), 502
    except Exception as e:
        logger.error(f'AI warrant generation failed: {e}')
        return jsonify({'success': False, 'error': 'Warrant generation failed. Try again.'}), 500


@app.route('/api/ai/generate-call', methods=['POST'])
def ai_generate_call():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured.'}), 503

    data = request.get_json(silent=True) or {}
    call_type = data.get('callType', '').strip()

    system_msg = """You are an AI-powered Computer Aided Dispatch (CAD) system for NThaCityRP, a GTA V roleplay server set in Los Santos.
CALL GENERATION MODE: Generate fully realistic GTA V emergency calls.
LOCATION RULES (CRITICAL): ALL locations must be real GTA V map areas — Davis, Strawberry, Mission Row, Vespucci, Del Perro, Mirror Park, Rockford Hills, Sandy Shores, Paleto Bay, Route 68, Senora Freeway, Great Ocean Highway, Legion Square, Pillbox Hill Medical Center, Maze Bank Arena, LSIA, La Mesa, Cypress Flats, etc.
DISPATCH LOGIC: Assign LSPD units (LSPD-1A23, LSPD-2B04) for city calls, BCSO (BCSO-3C11) for county/highway, K9-01/K9-02, AIR-1 for helicopter. Escalate priority based on severity.
Generate realistic caller names (first + last). The transcript must feel like a real 911 call — dispatcher asks clarifying questions, caller may be panicked or calm depending on incident. No real-world references."""

    type_hint = f" The call type should be: {call_type}." if call_type else " Pick a random realistic incident type."

    user_msg = f"""Generate a complete GTA V 911 emergency call for an LSPD dispatch session.{type_hint}

Respond with ONLY a valid JSON object with these exact keys:
- "callType": the incident type (e.g. "Shots Fired", "Traffic Accident", "Armed Robbery", "Domestic Disturbance", "Pursuit", "Suspicious Person", "Drug Activity", "Assault in Progress")
- "caller": realistic full name of the caller
- "location": specific GTA V street, area, or landmark (e.g. "Forum Drive & Covenant Ave, Davis" or "Route 68 near Harmony")
- "description": 2-3 sentences of what the caller describes to dispatch
- "dispatchNotes": 1-2 sentences of internal dispatcher notes (unit recommendation, hazards, backup needed)
- "priority": one of "Critical", "High", "Medium", "Low"
- "assignedUnit": LSPD/BCSO unit designation (e.g. "LSPD-1A23", "BCSO-2B11", "AIR-1", "K9-02")
- "transcript": an array of 6-10 objects, each with "speaker" ("Dispatch" or "Caller") and "line" (the spoken dialogue). Make it realistic — dispatcher confirms location, caller may be scared or urgent, dispatcher gives instructions and confirms unit en route.

Respond only with the JSON object. No markdown, no extra text."""

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [
                {'role': 'system', 'content': system_msg},
                {'role': 'user', 'content': user_msg}
            ],
            'max_tokens': 800,
            'temperature': 0.9,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://openrouter.ai/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=25) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            return jsonify({'success': True, 'call': ai_json})
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter generate-call error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}.'}), 502
    except Exception as e:
        logger.error(f'AI call generation failed: {e}')
        return jsonify({'success': False, 'error': 'Call generation failed. Try again.'}), 500


@app.route('/api/ai/incident-summary', methods=['POST'])
def ai_incident_summary():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured.'}), 503

    data = request.get_json(silent=True) or {}
    notes = data.get('notes', '').strip()

    if not notes:
        return jsonify({'success': False, 'error': 'No CAD notes provided.'}), 400

    system_msg = """You are an AI-powered Computer Aided Dispatch (CAD) system and report-writing assistant for NThaCityRP, a GTA V roleplay server set in Los Santos.
LOCATION RULES (CRITICAL): ALL locations must reference GTA V map areas — Davis, Strawberry, Mission Row, Vespucci, Del Perro, Mirror Park, Route 68, Senora Freeway, Legion Square, Pillbox Hill, Maze Bank Arena, etc. Convert any vague or real-world locations to the closest GTA V equivalent.
OUTPUT: Generate Discord-formatted (#criminal-files channel) summaries. Use INCIDENT REPORT MODE structure. Professional law enforcement tone only."""

    user_msg = f"""An officer has provided raw CAD notes. Generate a clean Discord-formatted incident summary for the #criminal-files channel.

Rules:
- Use **bold** for all section labels
- Use a `code block` only for case/report numbers if present
- Max 200 words
- Sections (include if data available): **Incident Type**, **Location** (GTA V formatted), **Date/Time**, **Officers Involved**, **Unit(s)**, **Suspect(s)**, **Charges**, **Outcome**, **Notes**
- End with: ―――――――――――――――――――――
- Raw Discord markdown only — no wrapper blocks

Raw CAD Notes:
{notes}

Respond with ONLY a valid JSON object with one key:
- "summary": the full Discord-formatted incident summary string"""

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [
                {'role': 'system', 'content': system_msg},
                {'role': 'user', 'content': user_msg}
            ],
            'max_tokens': 500,
            'temperature': 0.4,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://openrouter.ai/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            return jsonify({'success': True, 'summary': ai_json.get('summary', '')})
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter incident summary error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}.'}), 502
    except Exception as e:
        logger.error(f'AI incident summary failed: {e}')
        return jsonify({'success': False, 'error': 'Summary failed. Try again.'}), 500


@app.route('/api/ai/suspect-match', methods=['POST'])
def ai_suspect_match():
    api_key = os.environ.get('OPENROUTER_API_KEY', '')
    if not api_key:
        return jsonify({'success': False, 'error': 'OPENROUTER_API_KEY not configured.'}), 503

    data = request.get_json(silent=True) or {}
    description = data.get('description', '').strip()
    civilians = data.get('civilians', [])

    if not description:
        return jsonify({'success': False, 'error': 'No description provided.'}), 400

    if not civilians:
        return jsonify({'success': True, 'matches': [], 'note': 'No civilians registered in the system yet.'})

    civ_list = '\n'.join([
        f"- Name: {c.get('firstName','?')} {c.get('lastName','?')} | DOB: {c.get('dob','?')} | Gender: {c.get('gender','?')} | Occupation: {c.get('occupation','?')} | Notes: {c.get('notes','')}"
        for c in civilians[:50]
    ])

    system_msg = """You are an AI-powered suspect identification assistant for NThaCityRP, a GTA V roleplay server set in Los Santos.
You help LSPD officers cross-reference physical suspect descriptions against the civilian registry. Be precise and analytical. Only match civilians where there is genuine physical basis. Maintain professional law enforcement tone."""

    user_msg = f"""An LSPD officer has provided a physical description of a suspect spotted in Los Santos. Cross-reference the registered civilian database and return the top matches.

Respond with ONLY a valid JSON object with one key:
- "matches": array of up to 3 objects, each with:
  - "name": full civilian name
  - "confidence": "High", "Medium", or "Low"
  - "reason": one short sentence (max 15 words) citing specific matching physical traits

If no civilians reasonably match, return an empty matches array.

Suspect Description: {description}

Registered Civilians:
{civ_list}

Respond only with the JSON object. No markdown, no extra text."""

    try:
        payload = json.dumps({
            'model': 'openai/gpt-4o-mini',
            'messages': [
                {'role': 'system', 'content': system_msg},
                {'role': 'user', 'content': user_msg}
            ],
            'max_tokens': 300,
            'temperature': 0.3,
            'response_format': {'type': 'json_object'}
        }).encode('utf-8')

        req = urllib.request.Request(
            'https://openrouter.ai/api/v1/chat/completions',
            data=payload,
            headers={
                'Content-Type': 'application/json',
                'Authorization': f'Bearer {api_key}',
                'HTTP-Referer': 'https://nthacityrp.com',
                'X-Title': 'NThaCityRP Police CAD'
            },
            method='POST'
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            result = json.loads(resp.read().decode('utf-8'))
            ai_json = json.loads(result['choices'][0]['message']['content'])
            return jsonify({'success': True, 'matches': ai_json.get('matches', [])})
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf-8', errors='replace')
        logger.error(f'OpenRouter suspect match error: {e.code} {body}')
        return jsonify({'success': False, 'error': f'OpenRouter error {e.code}.'}), 502
    except Exception as e:
        logger.error(f'AI suspect match failed: {e}')
        return jsonify({'success': False, 'error': 'Match failed. Try again.'}), 500


@app.route('/api/officer-sessions', methods=['GET'])
def get_officer_sessions():
    return jsonify({'sessions': load_officer_sessions()})


@app.route('/api/officer-session', methods=['POST'])
def post_officer_session():
    data = request.get_json(silent=True) or {}
    callsign = data.get('callsign', '').strip()
    name = data.get('name', '').strip()
    department = data.get('department', 'LSPD').strip()
    if not callsign:
        return jsonify({'success': False, 'error': 'callsign required'}), 400
    sessions = load_officer_sessions()
    sessions[callsign] = {
        'callsign': callsign,
        'name': name,
        'department': department,
        'loggedInAt': datetime.now().isoformat(),
        'status': 'On Duty',
    }
    save_officer_sessions(sessions)
    logger.info(f"Officer login: {callsign} ({name}) — {department}")
    return jsonify({'success': True})


@app.route('/api/officer-session/<callsign>', methods=['DELETE'])
def delete_officer_session(callsign):
    sessions = load_officer_sessions()
    sessions.pop(callsign, None)
    save_officer_sessions(sessions)
    logger.info(f"Officer end shift: {callsign}")
    return jsonify({'success': True})


@app.route('/api/alerts', methods=['GET'])
def get_alerts():
    since = request.args.get('since', '')
    alerts = load_alerts()
    if since:
        alerts = [a for a in alerts if a.get('issuedAt', '') > since]
    return jsonify({'alerts': alerts[-20:]})


@app.route('/api/alert', methods=['POST'])
def post_alert():
    data = request.get_json(silent=True) or {}
    alert_type = data.get('type', '').strip()
    message = data.get('message', '').strip()
    issued_by = data.get('issuedBy', 'Dispatch').strip()
    valid_types = ['PANIC', 'BOLO', 'ALL UNITS', 'CODE RED']
    if not alert_type or not message:
        return jsonify({'success': False, 'error': 'type and message are required'}), 400
    if alert_type not in valid_types:
        return jsonify({'success': False, 'error': f'Invalid type. Must be one of: {", ".join(valid_types)}'}), 400
    alerts = load_alerts()
    alert = {
        'id': f"ALERT-{datetime.now().strftime('%Y%m%d%H%M%S')}-{len(alerts)+1:04d}",
        'type': alert_type,
        'message': message,
        'issuedBy': issued_by,
        'issuedAt': datetime.now().isoformat(),
    }
    alerts.append(alert)
    save_alerts(alerts)
    logger.info(f"Alert broadcast: {alert['id']} — {alert_type} by {issued_by}")
    return jsonify({'success': True, 'alert': alert})


@app.route('/api/cad/data', methods=['GET'])
def get_cad_data():
    return jsonify(load_cad_data())


@app.route('/api/cad/data', methods=['POST'])
def post_cad_data():
    data = request.get_json(silent=True)
    if not isinstance(data, dict):
        return jsonify({'success': False, 'error': 'Invalid payload'}), 400
    allowed_keys = {'civilians', 'vehicles', 'licenses', 'warrants', 'arrests',
                    'incidents', 'evidence', 'trafficStops', 'calls911', 'officers', 'activityLog'}
    cleaned = {k: v for k, v in data.items() if k in allowed_keys}
    existing = load_cad_data()
    existing.update(cleaned)
    save_cad_data(existing)
    return jsonify({'success': True})


@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def serve_static(path):
    if path == '':
        return send_from_directory('.', 'index.html')
    if os.path.exists(os.path.join('.', path)):
        return send_from_directory('.', path)
    return send_from_directory('.', 'index.html')


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=False)
